### PR TITLE
Fixing the recipe to compile C++ code and adding me as a maintainer

### PR DESCRIPTION
**Pull request by PrimozGodec**

### CODE REVIEW

**Comment by PrimozGodec** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
Looks like you need to add a file called `recipe/yum_requirements.txt` containing:
```
mesa-libGL
```

**Comment by PrimozGodec** [comment]
@chrisburr Thank you for the suggestion. I added the file but the error still stays. Did I forget anything?

**Comment by chrisburr** [comment]
I think it might need a rerender...

@conda-forge-admin, please rerender

**Comment by mariusvniekerk** [comment]
You may want to incorporate the changes in #9

**Comment by PrimozGodec** [comment]
I think this PR is ready to merge. @kernc or @astaric, can you merge it?

**Comment by kernc** [comment]
@astaric, can you? I can't.

**Pull request merged**
