### PR TITLE
Bump to 1.3.1

### PR DESCRIPTION
**Pull request by kernc**

### CODE REVIEW

**Comment by kernc** [comment]
@conda-forge-admin, please rerender.

**Comment by isuruf** [comment]
Can you change the numpy requirements to be like,
```
build:
  - numpy 1.11.*
run:
  - numpy >=1.11
```
?

**Comment by kernc** [comment]
Huh? How do you know it needs 1.11 to build and why so strict? Project's setup.py says numpy>=1.8.0.

**Comment by isuruf** [comment]
See https://conda-forge.org/docs/meta.html#building-against-numpy
We build with the oldest version of numpy that we support, so that it is compatible for all later versions

**Comment by kernc** [comment]
Thanks.

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by kernc** [comment]
@isuruf Thanks for the help and examples!

**Pull request merged**
